// <auto-generated />
using System;
using Covid19Management.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Covid19Management.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Covid19Management.Models.Citizen", b =>
                {
                    b.Property<int>("CitizenCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CitizenCode"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DiaChi");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime")
                        .HasColumnName("NgaySinh");

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("char(9)")
                        .HasColumnName("CMND");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("HoTen");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SoDienThoai");

                    b.HasKey("CitizenCode");

                    b.ToTable("CONGDAN");
                });

            modelBuilder.Entity("Covid19Management.Models.Vaccination", b =>
                {
                    b.Property<int>("VaccinationCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTC");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaccinationCode"));

                    b.Property<int?>("CitizenCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("FirstInjectDay")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTiemMui1");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("GhiChu");

                    b.Property<DateTime>("SecondInjectDay")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTiemMui2");

                    b.Property<DateTime>("SecondInjectRegisterDay")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayDKTiemMui2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TrangThai");

                    b.Property<int?>("VacxinCode")
                        .HasColumnType("int");

                    b.HasKey("VaccinationCode");

                    b.HasIndex("CitizenCode");

                    b.HasIndex("VacxinCode");

                    b.ToTable("TIEMCHUNG");
                });

            modelBuilder.Entity("Covid19Management.Models.Vacxin", b =>
                {
                    b.Property<int>("VacxinCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaLieuVX");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VacxinCode"));

                    b.Property<int>("BatchNumber")
                        .HasColumnType("int")
                        .HasColumnName("SoLo");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayHetHan");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayNhap");

                    b.Property<DateTime>("ManufacturingDate")
                        .HasColumnType("datetime")
                        .HasColumnName("NgaySanXuat");

                    b.Property<int?>("VacxinTypeCode")
                        .HasColumnType("int");

                    b.HasKey("VacxinCode");

                    b.HasIndex("VacxinTypeCode");

                    b.ToTable("LIEUVACXIN");
                });

            modelBuilder.Entity("Covid19Management.Models.VacxinType", b =>
                {
                    b.Property<int>("VacxinTypeCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaLoaiVX");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VacxinTypeCode"));

                    b.Property<int>("InjectDaysNumber")
                        .HasColumnType("int")
                        .HasColumnName("SoNgayTiemNhac");

                    b.Property<string>("ManufacturingCountry")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NuocSX");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TenLoaiVX");

                    b.HasKey("VacxinTypeCode");

                    b.ToTable("LOAIVACXIN");
                });

            modelBuilder.Entity("Covid19Management.Models.Vaccination", b =>
                {
                    b.HasOne("Covid19Management.Models.Citizen", "Citizen")
                        .WithMany("Vaccinations")
                        .HasForeignKey("CitizenCode");

                    b.HasOne("Covid19Management.Models.Vacxin", "Vacxin")
                        .WithMany("Vaccinations")
                        .HasForeignKey("VacxinCode");

                    b.Navigation("Citizen");

                    b.Navigation("Vacxin");
                });

            modelBuilder.Entity("Covid19Management.Models.Vacxin", b =>
                {
                    b.HasOne("Covid19Management.Models.VacxinType", "VacxinType")
                        .WithMany("Vacxins")
                        .HasForeignKey("VacxinTypeCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("VacxinType");
                });

            modelBuilder.Entity("Covid19Management.Models.Citizen", b =>
                {
                    b.Navigation("Vaccinations");
                });

            modelBuilder.Entity("Covid19Management.Models.Vacxin", b =>
                {
                    b.Navigation("Vaccinations");
                });

            modelBuilder.Entity("Covid19Management.Models.VacxinType", b =>
                {
                    b.Navigation("Vacxins");
                });
#pragma warning restore 612, 618
        }
    }
}
